# -*- coding: utf-8 -*-
"""Visualization design

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DKeQaFAyyJuUOfQeF_J6FwxDmskj4Q8y

### 1. Problem statement and question to answer
The objective of this study is to visualize and analyze the differences in Consolidated Surplus/Deficit before and after the issuance/repayment of government bonds and notes for each month in the Financial Year 2023-24. The problem at hand is to identify an appropriate plot type that can effectively showcase these variations and provide meaningful insights into the financial performance of the given period. The plot is designed to depict the changes in Consolidated Surplus/Deficit, enabling the government to understand the impact of bond issuance/repayment on the overall financial situation. By addressing this problem, we aim to enhance decision-making processes and gain valuable insights into the financial dynamics of the Financial Year 2023-24.

**Question:** How would you effectively illustrate the variations in Consolidated Surplus/Deficit before and after the issuance/repayment of government bonds and notes for each month in the Financial Year 2023-24?

### 2. Visualization results and write-up
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv('press_release_2023-24_e.csv')

months = data['Month']
before_issuance = data['Consolidated Surplus/ (Deficit) for the month before issuance/ repayment of government bonds and notes ']
after_issuance = data['Consolidated Surplus/ (Deficit) for the month after issuance/ repayment of government bonds and notes ']

difference = after_issuance - before_issuance

bar_width = 0.35

indices = np.arange(len(months))

plt.bar(indices, before_issuance, bar_width, label='Before Issuance/Repayment', color = 'purple')

plt.bar(indices + bar_width, after_issuance, bar_width, label='After Issuance/Repayment', color = 'violet')

plt.plot(indices + bar_width / 2, difference, linestyle='-', color='red', label='Difference that bonds created')

plt.xlabel('Month')
plt.ylabel('Consolidated Surplus/Deficit')
plt.title('Consolidated Surplus/Deficit Before and After Issuance/Repayment for Each Month For Financial Year 2023-24')

plt.xticks(indices + bar_width / 2, months, rotation=45)

plt.legend()

plt.tight_layout()
plt.show()

"""# Write-Up

The objective of this visualization is to effectively illustrate the trend created by the consolidated surplus/deficit before and after the issuance or repayment of government bonds for every month of the financial year 2023-24 (Data available till December).

In this regard, we decided to use a combination of bar charts and line plots. The bar graphs represent the consolidated surplus/deficit before and after the issuance/repayment while the line plot illustrates the difference between them. We chose this particular design to enable the viewer to make a clear visual comparison between the two periods along with highlighting the effects of bond issuance and repayment.

The x-axis represents the months of the financial year while the y-axis represents the consolidated surplus/deficit. The bar graphs are placed side-by-side with the same bar width to aid the comparison being made. The colours of the bar graph have been chosen to be different so that it is possible to make a distinction between the two periods and avoid confusion. However, these colours are relatively monotonic to make the design easier on the eyes and clearer. The line plot representing the difference is in red to make it stand out against the colours of the bar and emphasize the impact created by the bond issuance/repayment. A legend has been included to enhance clarity on the different components of the visualization. Clear labels have also been used to clarify the meaning of each element in the illustration.

All of this combined, communicates the story of the effects of bond issuance and repayment on government surplus and deficit. It allows decision-makers and analysts to quickly identify a trend as well as identify months where bonds had the most and least impact on the financial situation. This can help make informed financial decisions in the future. However, it is also important to take into account that this visualization does not provide a detailed breakdown of other factors that might influence the government’s financial position. Therefore, additional analysis as well as complementary illustrations may be necessary when trying to understand the overall financial situation during the year.

### 3. Appendices

#### Visualization Process
We used the matplotlib, a plotting library in python. We first read the CSV file for 2023-24 financial year and extracted the relevant columns [month, Consolidated Surplus/ (Deficit) for the month before issuance/ repayment of government bonds and notes and the Consolidated Surplus/ (Deficit) for the month after issuance/ repayment of government bonds and notes]. Then we calculated the difference between surplus/(deficit) before issuance and after issuance of bonds. Then we selected a set bar width throughout. Then we created an array to be used as the indices for positioning the bars in the bar graph. Then we create two consecutive bar graphs for Consolidated Surplus/ (Deficit) for the month before issuance/ repayment of government bonds and notes and the Consolidated Surplus/ (Deficit) for the month after issuance/ repayment of government bonds and notes and then added a line plot to represent the difference between them. And then we added the labels to the axises and added a legend. Then had the program output the graph as appropriate.
"""